package com.example.userlist

import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat
import androidx.fragment.app.Fragment
import com.example.userlist.databinding.ActivityMainBinding
import com.example.userlist.features.ProfileFragment
import com.example.userlist.features.UsersFragment
import dagger.hilt.android.AndroidEntryPoint

@AndroidEntryPoint
class MainActivity : AppCompatActivity() {
    private lateinit var binding: ActivityMainBinding
    private var activeFragment: Fragment? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        // ActivityMainBinding is a class automatically generated by Android from your activity_main.xml file.
        // '.inflate(layoutInflater)' turns that XML layout file into a real "Living" Java/Kotlin object.
        // We store this in the 'binding' variable so we can access any View by its ID (e.g., binding.myButton).
        binding = ActivityMainBinding.inflate(layoutInflater)

        // call @+id/main
        setContentView(binding.root)

        // Set the listener on the navigation buttons
        binding.bottomNavigation.setOnItemSelectedListener { item ->
            when (item.itemId) {
                R.id.navigation_home -> {
                    switchFragment("HOME")
                    true// Return true to visually select the item in the UI
                }

                R.id.navigation_profile -> {
                    switchFragment("PROFILE")
                    true
                }

                else -> false
            }
        }

        // Only load the first fragment if this is a fresh start
        if (savedInstanceState == null) {
            switchFragment("HOME")
        }

        ViewCompat.setOnApplyWindowInsetsListener(binding.toolbar) { v, insets ->
            val systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars())
//            v.updatePadding(top = systemBars.top)
            insets
        }
    }

    private fun switchFragment(tag: String) {
        val fm = supportFragmentManager

        // Reuse or create fragment : check if fragment already exists in memory
        val targetFragment: Fragment = fm.findFragmentByTag(tag) ?: when (tag) {
            "HOME" -> UsersFragment()
            "PROFILE" -> ProfileFragment()
            else -> UsersFragment()
        }

        // Instead of removing the previous fragment hide its view
        // This preserves the scroll position and any unsaved data in the fragment
        val transaction = fm.beginTransaction()
        activeFragment?.let { transaction.hide(it) }

        // If it's the first tine visiting this tab, we must add it to the container
        // If it was visited again we just show it again
        if (!targetFragment.isAdded) {
            transaction.add(R.id.fragmentContainer, targetFragment, tag)
        } else {
            transaction.show(targetFragment)
        }
        transaction.commit()
        activeFragment = targetFragment
    }
}